name: Build & Test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build & Test
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 10.15.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test
